// Danh sách loại tài nguyên cố định cho toàn hệ thống
export const RESOURCE_TYPES = [
  'Phòng họp',
  'Hội trường',
  'Thiết bị trình chiếu',
  'Máy chiếu',
  'Màn hình',
  'Loa',
  'Micro',
  'Bàn',
  'Ghế',
  'Xe đưa đón',
  'Máy in',
  'Máy tính',
  'Máy scan',
  'Nhà ăn',
  'Khu vực ăn uống',
  'Ký túc xá',
  'Chỗ ở',
  'Dụng cụ thể thao',
  'Dụng cụ y tế',
  'Tài liệu',
  'Sách',
  'Giáo trình',
  'Khu vực triển lãm',
  'Booth',
  'Âm thanh ánh sáng',
  'Dụng cụ vệ sinh',
  'Khác',
];
